name: mypaper
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.10
    - flake8=3.8.3
    - snakemake-minimal=7.8.5
    - seaborn=0.11.2
    - graphviz=2.50.0
    - tabulate<0.9.0
    - pathlib

