name: default
channels:
    - conda-forge
dependencies:
    - python=3.10
    - numpy=1.22.3
    - pandas=1.4.1
    - matplotlib=3.5.1
    - seaborn=0.11.2
    - tabulate<0.9.0
    - geopandas=0.12.0
    - rasterio=1.3.3
    - rasterstats=0.17.0
    - pathlib=1.0.1
    - zipfile2=0.0.12
    - requests=2.28.1
    - xarray=2022.10.0
    - click=8.1.3
    - netCDF4=1.6.1
    - PyGEOS=0.13
    - shapely=1.8.5
    - pycountry
    - xlrd>=1.0.0
    - openpyxl=3.0.10
    - scipy=1.9.3
    - pip:
        - cdsapi